export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SET_LOGIN = 'SET_LOGIN';

export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';
export const GET_USERDATA_FAILURE = 'GET_USERDATA_FAILURE';

export const GET_AGORA_TOKEN_SUCCESS = 'GET_AGORA_TOKEN_SUCCESS';
export const GET_AGORA_TOKEN_FAILURE = 'GET_AGORA_TOKEN_FAILURE';
