export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SET_LOGIN = 'SET_LOGIN';

export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';
export const GET_USERDATA_FAILURE = 'GET_USERDATA_FAILURE';

export const GET_AGORA_TOKEN_SUCCESS = 'GET_AGORA_TOKEN_SUCCESS';
export const GET_AGORA_TOKEN_FAILURE = 'GET_AGORA_TOKEN_FAILURE';

export const GET_AGORA_STREAM_SUCCESS = 'GET_AGORA_STREAM_SUCCESS';
export const GET_AGORA_STREAM_FAILURE = 'GET_AGORA_STREAM_FAILURE';

export const START_RECORD_AGORA_STREAM_SUCCESS = 'START_RECORD_AGORA_STREAM_SUCCESS';
export const START_RECORD_AGORA_STREAM_FAILURE = 'START_RECORD_AGORA_STREAM_FAILURE';

export const STOP_RECORD_AGORA_STREAM_SUCCESS = 'STOP_RECORD_AGORA_STREAM_SUCCESS';
export const STOP_RECORD_AGORA_STREAM_FAILURE = 'STOP_RECORD_AGORA_STREAM_FAILURE';